<div>
    <div>Your payment with GetFinancing failed</div>
<?php 

$gfData = $this->getData('gf_response');
if (isset($gfData["error"]) && isset($gfData["reasons"])): ?>
<div>
    <strong>Error: <?php 
        echo $gfData["error"] . " ". implode (", ", $gfData["subjects"]); 
        ?></strong>
</div>
<?php
endif; 

if (isset($gfData["amount"])): ?>
    <div>
        Amount: <strong><?php echo $gfData["amount"]; ?></strong>
    </div>
<?php
endif;

if (isset($gfData["inv_id"])): ?>
    <div>
        Your GetFinancing order ID: <strong><?php echo $gfData["inv_id"]; ?></strong>
    </div>
<?php
endif;
?>
</div>