#!/bin/sh
set -e

/usr/local/bin/load_db.sh

ln -sf /dev/stdout /var/log/apache2/error.log
ln -sf /dev/stdout /var/log/apache2/access.log

sed -i 's/ServerSignature On/ServerSignature Off/g' /etc/apache2/conf-enabled/security.conf

a2enmod rewrite 

echo " ------------------ CHECK CONNECTION TO DB ---------------"
/usr/local/bin/check-db-and-install.sh

echo " ------------------ Delete cache ---------------"
php bin/magento  cache:clean
php bin/magento  cache:flush
echo " ------------------ Cache deleted ---------------"

exec /usr/sbin/apachectl -D FOREGROUND
